---
- hosts: localhost
  tasks:
      - name: add keys
        apt_key:
            id: 1484120AC4E9F8A1A577AEEE97A80C63C9D8B80B
            state: present
            keyserver: keyserver.ubuntu.com

      - name: add apt repository
        apt_repository:
            repo: "deb [arch=amd64] https://pkg.osquery.io/deb deb main" 
            state: present
        
      - name: update apt packages
        apt:
            update_cache: yes

      - name: install osquery
        apt:
            name: osquery  
